In [209]:
##importing:
import numpy as np

In [9]:
# Initializing 1d array:
a = np.array([1,2,3,4])
print(a, type(a), a.dtype)

[1 2 3 4] <class 'numpy.ndarray'> int32


In [13]:
b = np.array([[9,8,8.0], [4.5,7.8,5]])
print(b, b.dtype)

[[9.  8.  8. ]
 [4.5 7.8 5. ]] float64


In [15]:
# get dimensions:
a.ndim
b.ndim

2

In [17]:
# get shapes:
print(a.shape, b.shape)

(4,) (2, 3)


In [20]:
# get types
c= np.array([1,4,45,7], dtype='int16')
print(a.dtype, b.dtype, c.dtype)

int32 float64 int16


In [27]:
# get sizes
print(a.itemsize,b.itemsize, c.itemsize) # itemsize => gives size in bytes

#total size
b.size + b.itemsize

4 8 2


14

## Accessing/ changing specific elements, rows, columns etc.

In [42]:
arr = np.array([
    [1, 2, 4, 5, 6,7,8,9],
    [4,5,8,9,96,4,5,4]
])

In [40]:
# Get a specific elements [row, column]
print(a[1], b[0,2])

2 8.0


In [37]:
# get specific rows:
b[0,:]

array([9., 8., 8.])

In [38]:
# Get specific columns:
b[:, 2]

array([8., 5.])

In [48]:
# [startindex: endindex: stepsize]
arr[0, 1:7:2]

array([2, 5, 7])

In [53]:
# Change the element:
arr[0,4]= 78
arr[:,2]= 777 
arr[:,3] =[44,55]
arr

array([[  1,   2, 777,  44,  78,   7,   8,   9],
       [  4,   5, 777,  55,  96,   4,   5,   4]])

In [57]:
### 3d examples:
d =np.array( [
    [
        [4, 5 , 6]
    ],
    [
        [7, 8 , 9]
    ]
])
d

array([[[4, 5, 6]],

       [[7, 8, 9]]])

In [66]:
# get specific element (work outside in)
print(d[0,0,2])
print(d[:,:,0])

6
[[4]
 [7]]


## Initilizing different types of arrays:

In [71]:
# all 0s matrix
np.zeros((2,3,1))

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [72]:
# All 1s matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [73]:
# Any other number
np.full((2,2), 84)

array([[84, 84],
       [84, 84]])

In [77]:
# Any other number (full_like)
np.full_like(d, 8) # or,
np.full(d.shape, 7)

array([[[7, 7, 7]],

       [[7, 7, 7]]])

In [79]:
# Radom decimal numbers
np.random.rand(4,2,2)

array([[[0.62933174, 0.83132471],
        [0.31695375, 0.2235839 ]],

       [[0.03519139, 0.41746705],
        [0.98456531, 0.56987281]],

       [[0.50364725, 0.54858644],
        [0.89561226, 0.89831139]],

       [[0.94653463, 0.84372658],
        [0.71755018, 0.62683002]]])

In [81]:
np.random.random_sample(d.shape)

array([[[0.75552814, 0.68838245, 0.48188021]],

       [[0.51558637, 0.04846191, 0.88967245]]])

In [85]:
# Random INtegers values:(start, end) => exclusive
np.random.randint(-4,7, size = (3,3))

array([[ 2, -1,  0],
       [ 4, -4,  3],
       [-1, -3,  0]])

In [86]:
# Indetity matrix => square...
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [95]:
# Repeat an array
arr = np.array([[1,2,3]]) # see when it is 1D array
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [107]:
# Array from image examples:
out = np.ones((5,5), dtype='int') #by default = int32
out[1:4,1:4] = 0
out[2,2] = 9
out

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [111]:
output = np.ones((5,5), dtype='int')
print(output)
z = np.zeros((3,3), dtype='int')
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Be careful when copying arrays!!

In [114]:
a = np.array([1, 2, 3])
b = a ## just reference is done. Not the copy
print(b)

[1 2 3]


In [115]:
b[0] = 100
print(a)  ## Here a also changed

[100   2   3]


In [117]:
# So use .copy()
c = a.copy()
print(c)

[100   2   3]


## Mathematics

In [124]:
a= np.array([1,2,3,4,5])
print(a+2, a-2,a/2, a**2)

[3 4 5 6 7] [-1  0  1  2  3] [0.5 1.  1.5 2.  2.5] [ 1  4  9 16 25]


In [125]:
# take sins:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

## Linear Algebra

In [129]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
b

[[1. 1. 1.]
 [1. 1. 1.]]


array([[2, 2],
       [2, 2],
       [2, 2]])

In [131]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [134]:
c= np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [138]:
a = np.array([[7,3,4,5], [2,3,4,8]])
a

array([[7, 3, 4, 5],
       [2, 3, 4, 8]])

In [142]:
# Min and max
print(np.min(a))
print(np.min(a, axis=1))
print(np.min(a, axis=0))


2
[3 2]
[2 3 4 5]


In [144]:
np.sum(a , axis= 0)
np.sum(a , axis= 1)

array([19, 17])

## Reorganizing the arrays

In [145]:
before = np.array([[7,3,4,5], [2,3,4,8]])
before.shape

(2, 4)

In [148]:
after = before.reshape((8,1)) #(4,2) , (2,2,2)
after

array([[7],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [8]])

In [151]:
## Vertically stacking vectors and matrices:
v1  = np.array([1,2,3,4,5])
v2  = np.array([6,4,5,8,9])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4, 5],
       [6, 4, 5, 8, 9],
       [6, 4, 5, 8, 9],
       [6, 4, 5, 8, 9]])

In [152]:
# Horizonal stack
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 4, 5, 8, 9])

## Miscellaneous

In [170]:
## Load from file:
file_data = np.genfromtxt('data.txt', delimiter=',')
file_data = file_data.astype('int')
file_data

array([[   123,    456,    789, 101112, 131415],
       [161718, 192021, 222324, 252627, 282930],
       [313233, 343536, 373839, 404142, 434445],
       [464748, 495051, 525354, 555657, 585960]])

## Boolean Masking and Advanced indexing:

In [173]:
file_data > 500  #other combinations also

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [178]:
# Only values greater than 500
file_data[file_data > 500]

array([   789, 101112, 131415, 161718, 192021, 222324, 252627, 282930,
       313233, 343536, 373839, 404142, 434445, 464748, 495051, 525354,
       555657, 585960])

In [186]:
# Can index with a list in NumPy:
a = np.array([1,3,35,6,9,0,43,2,5,6,78,6])
a[[1,3,5,10]]

array([ 3,  6,  0, 78])

In [195]:
# Any
np.any(file_data > 1000)
np.any(file_data > 1000, axis=0)

array([ True,  True,  True,  True,  True])

In [196]:
# All
np.all(file_data > 50)
np.all(file_data > 500,  axis= 0)

array([False, False,  True,  True,  True])

In [207]:
((file_data > 500) & (file_data < 5000 ))
(~(file_data > 500) & (file_data < 5000 ))

array([[ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [208]:
file_data

array([[   123,    456,    789, 101112, 131415],
       [161718, 192021, 222324, 252627, 282930],
       [313233, 343536, 373839, 404142, 434445],
       [464748, 495051, 525354, 555657, 585960]])

In [ ]:
file_data[]3 1 5 2
            3 5 2